version: '3'
services:
  db:
    container_name: "postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - development-network
    
  web:
    container_name: "django"
    build:
      context: ./web/
    env_file:
      - .env
    ports:
      - 8008:8000
    networks:
      - development-network
    depends_on:
      - db

  nginx:
    container_name: "nginx"
    build:
      context: ./nginx/
    ports:
      - 80:80
    networks:
      - development-network
    depends_on:
      - web

volumes:
  db-data:

networks:
    development-network:
        driver: bridge