name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web/requirements.txt

      - name: Run Migrations
        env:
          SECRET_KEY: ${{ secrets.DB_SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_SERVICE: ${{ secrets.DB_SERVICE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          cd web
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Test
        run: |
          pip install pytest
          pytest
          python manage.py test

      - name: Run lint with black
        run: |
          pip install black
          black .

    services:
      postgres_main:
        image: postgres
        env:
          SECRET_KEY: ${{ secrets.DB_SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_SERVICE: ${{ secrets.DB_SERVICE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
        ports:
          - 5432:5432
